# Site settings
title: RykerSun 的部落格
description: blogger
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rykersun.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: RykerSun
user_description: 
user_title: It's time to let go.
email: rykersun2002@gmail.com
twitter_username: rykersun
github_username:  rykersun
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

future: true

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主頁
    url: /
  - title: 分類
    url: /series
  - title: 標籤
    url: /tags
  - title: 關於
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
